#!/usr/bin/env zsh

## DIRECTORIES
alias cdc="cd ~/code" # Change directory to ~/code (main projects folder)
alias cdv="cd ~/code/bt-vue" # Change directory to personal project

## CONFIGS
alias a="code ~/code/dotfiles/_aliases" # Open _aliases in VSCode
alias css="code '$HOME/Library/Application Support/Code/User/vscode.css'" # Open CSS file for VSCode "Custom CSS and JS Loader" Extension https://github.com/be5invis/vscode-custom-css
alias f="code ~/code/dotfiles/_functions" # Open _functions in VSCode
alias gitconfig="code ~/code/dotfiles/.gitconfig" # Open .gitconfig file in VSCode
alias gitignore="code ~/code/dotfiles/.gitignore" # Open .gitignore file in VSCode
alias hosts="code /private/etc/hosts" # Open hosts file in VSCode
alias path='echo -e ${PATH//:/\\n}' # Print each PATH entry on a separate line
alias paths="code /etc/paths" # Open paths in VSCode
alias shells="code /etc/shells" # Open shells in VSCode
alias z="code ~/code/dotfiles/.zshrc" # Open .zshrc
alias z="code ~/code/dotfiles/.zshrc" # Open .zshrc in VSCode

## COMMANDS
alias assertions="pmset -g assertions | grep Prevent" # List processes keeping mac awake
alias brewls='brew list --versions $(brew leaves)' # List top-level Homebrew formulae, `brew help leaves` for detail
alias gpgls="gpg --list-secret-keys --keyid-format LONG" # List gpg keys
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder" # Clean up LaunchServices to remove duplicates in the “Open With” menu
alias npmls="npm list --global --depth=0" # List global NPM packages
alias out="npm outdated" # List outdated local NPM packages
alias parent="printf '$(ps -p $PPID)\n'" # Print parent process
alias r="exec ${SHELL} -l; src" # Reload the shell (i.e. invoke as a login shell); Reload oh_my_zsh https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/zsh_reload
alias symls="ls -lhaF | grep ^l" # List symlinks in current directory
