#!/usr/bin/env bash

## ANSI Color Escape Sequences
# BACKGROUND
black='\e[30m'  # Black
red='\e[31m'    # Red
green='\e[32m'  # Green
yellow='\e[33m' # Yellow
blue='\e[34m'   # Blue / Purple
pink='\e[35m'   # Pink / Magenta
cyan='\e[36m'   # Cyan
white='\e[37m'  # White
# FOREGROUND
blackb='\e[40m'  # Black
redb='\e[41m'    # Red
greenb='\e[42m'  # Green
yellowb='\e[43m' # Yellow
blueb='\e[44m'   # Blue / Purple
pinkb='\e[45m'   # Pink / Magenta
cyanb='\e[46m'   # Cyan
whiteb='\e[47m'  # White
# FORMATTING
bold='\e[1m\e[35m'   # Bold + Pink
dim='\e[2m'          # Half-bright
reset='\e[0m'        # Reset attributes
rev='\e[7m'          # Reverse text
standout='\e[3m'     # Standout
standoutrm='\e[22m'  # Standout remove
underline='\e[4m'    # Underline
underlinerm='\e[24m' # Underline remove

## TPUT
# Easy, clean, portable terminal colors (at the cost of slight performance)
# Example Usage:
# printf "I'm seeing ${red}red${reset}.\n"
# https://wiki.bash-hackers.org/scripting/terminalcodes#colors_using_tput
# # FOREGROUND
# black=$(tput setaf 0)  # Black
# blue=$(tput setaf 4)   # Blue / Purple
# cyan=$(tput setaf 6)   # Cyan
# green=$(tput setaf 2)  # Green
# pink=$(tput setaf 5)   # Pink / Magenta
# red=$(tput setaf 1)    # Red
# white=$(tput setaf 7)  # White
# yellow=$(tput setaf 3) # Yellow
# # BACKGROUND
# blackb=$(tput setab 0)  # Black
# blueb=$(tput setab 4)   # Blue / Purple
# cyanb=$(tput setab 6)   # Cyan
# greenb=$(tput setab 2)  # Creen
# pinkb=$(tput setab 5)   # Pink / Magenta
# redb=$(tput setab 1)    # Red
# whiteb=$(tput setab 7)  # White
# yellowb=$(tput setab 3) # Yellow
# # FORMATTING
# bold=$(tput setaf 5 && tput bold) # Bold
# dim=$(tput dim)                   # Half-bright
# reset=$(tput sgr0)                # Reset attributes
# rev=$(tput rev)                   # Reverse text
# standout=$(tput smso)             # Standout
# standoutrm=$(tput rmso)           # Standout remove
# underline=$(tput smul)            # Underline
# underlinerm=$(tput rmul)          # Underline remove
