#!/usr/bin/env zsh

export CODE="$HOME/CODE"           # Path to my code projects
export DOTS="$HOME/code/dotfiles"  # Path to my dotfiles
export EDITOR='code'               # Make VSCode the default editor
export LC_ALL='en_US.UTF-8'        # Use UTF-8
export ZSH="$HOME/.oh-my-zsh"      # Path to your oh-my-zsh installation.
# For compilers to find ruby (`brew info ruby`)
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"

## PATH
path=('/usr/local/sbin' $path) # Homebrew sbin
path=('/usr/local/bin' $path) # `which brew`
path=('/usr/local/opt/ruby/bin' $path) # `brew info ruby` caveat
path=('/usr/local/lib/ruby/gems/2.6.0/bin' $path) # `brew info ruby` caveat
path=("$DOTS/git-commands" $path) # enable Git subcommands file:///$HOME/code/dotfiles/git-home

# Bash Compatible
# export PATH="/usr/local/sbin:$PATH" # Homebrew sbin
# export PATH="/usr/local/bin:$PATH" # `which brew`
# export PATH="/usr/local/opt/ruby/bin:$PATH" # `brew info ruby` caveat
# export PATH="/usr/local/lib/ruby/gems/2.6.0/bin:$PATH" # `brew info ruby` caveat
# export PATH="$DOTS/git-commands:$PATH" # enable Git subcommands file:///$HOME/code/dotfiles/git-home

export PATH # export to sub-processes (make it inherited by child processes)