#!/usr/bin/env zsh

. ~/code/dotfiles/.colors

printf "Run$bold git yolo$reset? [${green}y$reset/${red}N$reset]: "
if read -q; then
  printf "\n${bold}git stage .$reset\n" && git stage .
  echo "${bold}git commit -m '$(curl -s whatthecommit.com/index.txt)'$reset..." && git commit -m "$(curl -s whatthecommit.com/index.txt)"
  printf "${bold}git push -f --all$reset..." && git push -f --all
  printf "${bold}git push -f --tags$reset..." && git push -f --tags
  echo "${bold}git fetch$reset..." && git fetch
else
  echo " $redb$black Aborting $reset $bold$funcstack[1]$reset..."
fi
