#!/usr/bin/env zsh

. ~/code/dotfiles/.colors

printf "Run$bold git yolo$reset? [${green}y$reset/${red}N$reset]: "
if read -q; then
  printf "${bold}git stage .$reset..." && git stage .
  printf "${bold}git commit -m \"$(curl -s whatthecommit.com/index.txt)\"$reset..." && git commit -m "$(curl -s whatthecommit.com/index.txt)"
  printf "${bold}git push -f --all$reset..." && git push -f --all
  printf "${bold}git push -f --tags$reset..." && git push -f --tags
  printf "${bold}git fetch$reset..." && git fetch
else
  echo " $redb$black Aborting $reset $bold$funcstack[1]$reset..."
fi
