#!/usr/bin/env zsh

getAction() {
  # https://git-scm.com/docs/git-status#_short_format
  case $1 in
  M)
    printf Modifiy
    ;;
  A | U | ??)
    printf Add
    ;;
  D)
    printf rm
    ;;
  R)
    printf Rename
    ;;
  C)
    printf Copy
    ;;
  *)
    printf $(curl -s whatthecommit.com/index.txt)
    ;;
  esac
}

commitsRaw=("${(@f)$(git status --porcelain)}")
filesRaw=($(git status --porcelain | awk '{print $2}'))
for i in $commitsRaw; do
  local actionLetter=$(echo $i | awk '{print $1}')
  local action=$(getAction $actionLetter)
  local fileRaw=$(echo $i | awk '{print $2}')
  local file=${fileRaw##*/}
  commits+=("$action $file")
done

commits=$(print -l "${(@)commits}")

printf "$commits\n Proceed with commits? [${green}y$reset/${red}N$reset]: "
  if read -q; then
    echo
    for i in $filesRaw; do
      # echo $i
      git add $i
    done
    for i in $commits; do
      # echo $i
      git commit -m $i
    done
  else
    echo " $redb$black Aborting $reset $bold$funcstack[1]$reset..."
fi