#!/usr/bin/env bash

. ~/code/dotfiles/.colors

# https://help.github.com/en/articles/syncing-a-fork
echo "${bold}git checkout master -q$reset..." && git checkout master -q
echo "${bold}git fetch upstream$reset..." && git fetch upstream
echo "${bold}git merge upstream/master$reset..." && git merge upstream/master
