#!/usr/bin/env zsh

case $1 in
commit | -c)
  printf "Run$bold git yolo commit$reset? [${green}y$reset/${red}N$reset]: "
  if read -q; then
    printf "\n${bold}git stage .$reset\n" && git stage .
    echo "${bold}git commit -m \"$(curl -s whatthecommit.com/index.txt)\"$reset" && git commit -m "$(curl -s whatthecommit.com/index.txt)"
    printf "${bold}git push -f --all$reset... " && git push -f --all
    printf "${bold}git push -f --tags$reset... " && git push -f --tags
    echo "${bold}git fetch$reset" && git fetch
  else
    echo " $redb$black Aborting $reset $bold$funcstack[1]$reset..."
  fi
  ;;
*)
  printf "Run$bold git yolo sync$reset? [${green}y$reset/${red}N$reset]: "
  if read -q; then
    printf "${bold}git push -f --all$reset... " && git push -f --all
    printf "${bold}git push -f --tags$reset... " && git push -f --tags
    echo "${bold}git fetch$reset" && git fetch
  else
    echo " $redb Aborting $reset$bold$funcstack[1]$reset..."
  fi
  ;;
esac
