#!/usr/bin/env zsh

# if [ ! $1 ]; then
#   open $(git config remote.origin.url)
# else
#   open "https://github.com/$1"
# fi

if [[ ! $1 ]]; then
  open $(git config remote.origin.url)
else
  open "https://github.com/$1"
fi
